// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstallResult is the structured outcome of an Install/Uninstall operation,
 * designed to be shown to the user. Command is the exact command line that was
 * (or would be) run; Output is npm's combined stdout+stderr.
 */
export interface InstallResult {
    "id": string;
    "action": string;
    "command": string;
    "output": string;
    "ok": boolean;
    "error"?: string;
}

/**
 * ModelOption is one advertised model returned by the models fetch: its
 * canonical ID plus the optional human-friendly display name the endpoint
 * advertises. Never secret — safe to return to the frontend.
 */
export interface ModelOption {
    "id": string;
    "display_name"?: string;
}

/**
 * ProviderRef is the minimal non-secret reference to one provider (for
 * per-tool dropdowns): ID, display name and whether it is the globally
 * active provider — never any part of the key value, not even masked.
 */
export interface ProviderRef {
    "id": string;
    "name": string;
    "active": boolean;
}

/**
 * ProviderView is the non-secret view of one managed provider returned to
 * the frontend. It never carries any API key value; HasKey reports whether
 * one is stored.
 */
export interface ProviderView {
    "id": string;
    "name": string;
    "note": string;
    "base_url": string;
    "models": string[] | null;

    /**
     * ModelNames maps a member of Models to its optional display name, used only
     * for UI labels. Missing entries fall back to the model ID.
     */
    "model_names": { [_ in string]?: string } | null;
    "model": string;
    "small_fast_model": string;

    /**
     * OpusModel, SonnetModel and HaikuModel are the provider's optional Claude
     * Code tier pins; empty means the tier follows the default Model.
     */
    "opus_model": string;
    "sonnet_model": string;
    "haiku_model": string;
    "has_key": boolean;
    "active": boolean;
}

/**
 * ToolOpResult is the per-tool outcome of a bulk apply/restore operation.
 */
export interface ToolOpResult {
    "id": string;
    "ok": boolean;
    "message"?: string;
    "error"?: string;
}

/**
 * ToolView is the per-tool summary returned by [Service.ListTools].
 */
export interface ToolView {
    "id": string;
    "name": string;
    "installed": boolean;
    "status": string;
    "detail": string;
    "config_paths": string[] | null;

    /**
     * Models is the active profile's selectable model list (with backward-compat
     * seeding from the selected Model), used to populate the per-tool dropdown.
     * It is empty when no profile is saved.
     */
    "models": string[] | null;

    /**
     * ModelNames maps a member of Models to its optional display name, used only
     * for dropdown labels. Missing entries fall back to the model ID.
     */
    "model_names": { [_ in string]?: string } | null;

    /**
     * SelectedModel is the effective model that has been (or would be) applied to
     * this tool: the per-tool override when set, otherwise the profile default.
     * It is empty when no profile is saved.
     */
    "selected_model": string;

    /**
     * Providers is the provider list (ID + name + active flag, never key
     * values), used to populate the per-tool provider dropdown. It is empty
     * when no provider is configured.
     */
    "providers": ProviderRef[] | null;

    /**
     * SelectedProviderID is the ID of the provider in effect for this tool:
     * the per-tool override when set and still a member, otherwise the active
     * provider. It is empty when no provider is configured.
     */
    "selected_provider_id": string;

    /**
     * ProviderName is the display name of the provider in effect for this
     * tool. It never carries any part of the key value.
     */
    "provider_name": string;

    /**
     * ProviderOverridden is true when the provider in effect comes from a
     * per-tool override rather than the active provider.
     */
    "provider_overridden": boolean;

    /**
     * ApplyMode is the tool's apply mode: "all" applies every model of the
     * effective provider, "one" (the default) applies only the selected model.
     */
    "apply_mode": string;

    /**
     * Installable is true when the tool has a whitelisted npm package the
     * installer can install/uninstall. It is false for tools distributed only as
     * a standalone binary, so the UI can hide the Install action for those.
     */
    "installable": boolean;
}

/**
 * UninstallPlan is the non-secret, read-only preview returned by
 * [Service.PlanUninstall]. Command and Target are display-only; execution
 * accepts only a tool ID and resolves a fresh plan.
 */
export interface UninstallPlan {
    "method": string;
    "action": string;
    "command": string;
    "target": string;
    "warning": string;
    "can_execute": boolean;
}
