// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InstallResult is the structured outcome of an Install/Uninstall operation,
 * designed to be shown to the user. Command is the exact command line that was
 * (or would be) run; Output is npm's combined stdout+stderr.
 */
export interface InstallResult {
    "id": string;
    "action": string;
    "command": string;
    "output": string;
    "ok": boolean;
    "error"?: string;
}

/**
 * ProfileView is the non-secret view of the active profile returned to the
 * frontend. It never carries the API key; HasKey reports whether one is stored.
 */
export interface ProfileView {
    "label": string;
    "base_url": string;
    "models": string[] | null;

    /**
     * ModelNames maps a member of Models to its optional display name, used only
     * for UI labels. Missing entries fall back to the model ID.
     */
    "model_names": { [_ in string]?: string } | null;
    "model": string;
    "small_fast_model": string;
    "has_key": boolean;
}

/**
 * ToolOpResult is the per-tool outcome of a bulk apply/restore operation.
 */
export interface ToolOpResult {
    "id": string;
    "ok": boolean;
    "message"?: string;
    "error"?: string;
}

/**
 * ToolView is the per-tool summary returned by [Service.ListTools].
 */
export interface ToolView {
    "id": string;
    "name": string;
    "installed": boolean;
    "status": string;
    "detail": string;
    "config_paths": string[] | null;

    /**
     * Models is the active profile's selectable model list (with backward-compat
     * seeding from the selected Model), used to populate the per-tool dropdown.
     * It is empty when no profile is saved.
     */
    "models": string[] | null;

    /**
     * ModelNames maps a member of Models to its optional display name, used only
     * for dropdown labels. Missing entries fall back to the model ID.
     */
    "model_names": { [_ in string]?: string } | null;

    /**
     * SelectedModel is the effective model that has been (or would be) applied to
     * this tool: the per-tool override when set, otherwise the profile default.
     * It is empty when no profile is saved.
     */
    "selected_model": string;

    /**
     * Installable is true when the tool has a whitelisted npm package the
     * installer can install/uninstall. It is false for tools distributed only as
     * a standalone binary, so the UI can hide the Install action for those.
     */
    "installable": boolean;
}
