// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallResult is the structured outcome of an Install/Uninstall operation,
 * designed to be shown to the user. Command is the exact command line that was
 * (or would be) run; Output is npm's combined stdout+stderr.
 */
export class InstallResult {
    "id": string;
    "action": string;
    "command": string;
    "output": string;
    "ok": boolean;
    "error"?: string;

    /** Creates a new InstallResult instance. */
    constructor($$source: Partial<InstallResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallResult($$parsedSource as Partial<InstallResult>);
    }
}

/**
 * MCPState is the redacted MCP state returned to the frontend. It carries a
 * HasKey flag (never the key itself) and the per-tool status list, plus the
 * non-secret endpoint that would be injected.
 */
export class MCPState {
    "has_key": boolean;
    "endpoint": string;
    "tools": MCPToolView[];

    /** Creates a new MCPState instance. */
    constructor($$source: Partial<MCPState> = {}) {
        if (!("has_key" in $$source)) {
            this["has_key"] = false;
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPState instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPState {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField2_0($$parsedSource["tools"]);
        }
        return new MCPState($$parsedSource as Partial<MCPState>);
    }
}

/**
 * MCPTestResult is the structured outcome of [Service.TestMCPConnection]. It
 * carries only display-safe fields and never includes the key or Authorization
 * header.
 */
export class MCPTestResult {
    "ok": boolean;
    "status": number;
    "meaning": string;

    /** Creates a new MCPTestResult instance. */
    constructor($$source: Partial<MCPTestResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("meaning" in $$source)) {
            this["meaning"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPTestResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPTestResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MCPTestResult($$parsedSource as Partial<MCPTestResult>);
    }
}

/**
 * MCPToolView is the per-tool MCP status returned by [Service.GetMCPState].
 */
export class MCPToolView {
    "id": string;
    "installed": boolean;
    "status": string;
    "detail": string;
    "config_paths": string[];

    /** Creates a new MCPToolView instance. */
    constructor($$source: Partial<MCPToolView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("config_paths" in $$source)) {
            this["config_paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPToolView instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPToolView {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config_paths" in $$parsedSource) {
            $$parsedSource["config_paths"] = $$createField4_0($$parsedSource["config_paths"]);
        }
        return new MCPToolView($$parsedSource as Partial<MCPToolView>);
    }
}

/**
 * ProfileView is the non-secret view of the active profile returned to the
 * frontend. It never carries the API key; HasKey reports whether one is stored.
 */
export class ProfileView {
    "label": string;
    "base_url": string;
    "models": string[];
    "model": string;
    "small_fast_model": string;
    "has_key": boolean;

    /** Creates a new ProfileView instance. */
    constructor($$source: Partial<ProfileView> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("small_fast_model" in $$source)) {
            this["small_fast_model"] = "";
        }
        if (!("has_key" in $$source)) {
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileView instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileView {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField2_0($$parsedSource["models"]);
        }
        return new ProfileView($$parsedSource as Partial<ProfileView>);
    }
}

/**
 * ToolOpResult is the per-tool outcome of a bulk apply/restore operation.
 */
export class ToolOpResult {
    "id": string;
    "ok": boolean;
    "message"?: string;
    "error"?: string;

    /** Creates a new ToolOpResult instance. */
    constructor($$source: Partial<ToolOpResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolOpResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolOpResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolOpResult($$parsedSource as Partial<ToolOpResult>);
    }
}

/**
 * ToolView is the per-tool summary returned by [Service.ListTools].
 */
export class ToolView {
    "id": string;
    "name": string;
    "installed": boolean;
    "status": string;
    "detail": string;
    "config_paths": string[];

    /**
     * Custom is true for user-defined tools managed by the generic JSON-template
     * adapter, false for the built-ins. The UI hides Install/Uninstall for these
     * and offers a Remove action instead.
     */
    "custom": boolean;

    /**
     * Models is the active profile's selectable model list (with backward-compat
     * seeding from the selected Model), used to populate the per-tool dropdown.
     * It is empty when no profile is saved.
     */
    "models": string[];

    /**
     * SelectedModel is the effective model that has been (or would be) applied to
     * this tool: the per-tool override when set, otherwise the profile default.
     * It is empty when no profile is saved.
     */
    "selected_model": string;

    /** Creates a new ToolView instance. */
    constructor($$source: Partial<ToolView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("config_paths" in $$source)) {
            this["config_paths"] = [];
        }
        if (!("custom" in $$source)) {
            this["custom"] = false;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("selected_model" in $$source)) {
            this["selected_model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolView instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolView {
        const $$createField5_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config_paths" in $$parsedSource) {
            $$parsedSource["config_paths"] = $$createField5_0($$parsedSource["config_paths"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField7_0($$parsedSource["models"]);
        }
        return new ToolView($$parsedSource as Partial<ToolView>);
    }
}

// Private type creation functions
const $$createType0 = MCPToolView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
