// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the backend façade bound into the Wails application.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddProvider validates and persists a new provider, returning its generated
 * ID. The name, API key value, base URL and default model are required
 * ([core.Provider.Validate] rules). The first provider added becomes active.
 * The key value is only persisted (keychain-first), never echoed back.
 */
export function AddProvider(p: core$0.Provider): $CancellablePromise<string> {
    return $Call.ByID(1254497234, p);
}

/**
 * ApplyAll applies the active profile to every installed tool and returns a
 * per-tool outcome. Tools that are not installed are skipped entirely (no
 * result entry): applying would otherwise create their config files — API key
 * included — for software that is not on the machine. It validates the saved
 * profile once up front and fails fast (returning an error, no partial
 * results) when no valid profile is saved. Individual adapter failures are
 * captured per tool and do not abort the run.
 */
export function ApplyAll(): $CancellablePromise<$models.ToolOpResult[] | null> {
    return $Call.ByID(3266725423);
}

/**
 * ApplyOne applies the active profile to the single tool identified by toolID,
 * honoring the per-tool model selection. It first validates the saved profile
 * and returns an error for an unknown tool or an invalid/missing profile.
 */
export function ApplyOne(toolID: string): $CancellablePromise<core$0.ApplyResult> {
    return $Call.ByID(1465759944, toolID);
}

/**
 * DismissOnboarding persists the dismissal of the first-run checklist so it
 * never reappears after a restart. It is deliberately one-way: the checklist
 * is a first-run aid, and un-dismissing has no UI.
 */
export function DismissOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(1273431029);
}

/**
 * FetchEndpointModels queries {baseURL}/models like [Service.FetchProviderModels]
 * but for endpoint values that may not be saved yet, so the Add/Edit dialog
 * can list models before the provider is persisted. It returns each model's
 * ID plus the display name the endpoint advertises (when any), so the dialog
 * can seed friendly names. The API key is transient: it is used only for this
 * one request and is never stored, logged, or included in errors. When apiKey
 * is blank and providerID names a stored provider, that provider's stored key
 * is used instead (the Edit flow, where the key never round-trips to the
 * frontend) — but only when the normalized baseURL matches the provider's
 * stored base URL, so a stored key can never be sent to an arbitrary
 * endpoint. Read-only: it never mutates settings, and errors stay
 * display-safe.
 */
export function FetchEndpointModels(baseURL: string, apiKey: string, providerID: string): $CancellablePromise<$models.ModelOption[] | null> {
    return $Call.ByID(4130773511, baseURL, apiKey, providerID);
}

/**
 * FetchProviderModels queries the stored provider's OpenAI-compatible
 * endpoint (GET {base_url}/models with a Bearer key) and returns the sorted,
 * de-duplicated model IDs it advertises. It is read-only: it never mutates
 * settings — the caller decides what to do with the list. Errors are
 * display-safe: they never include the API key, the Authorization header, or
 * the endpoint's response body.
 */
export function FetchProviderModels(providerID: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1566093931, providerID);
}

/**
 * Install installs the tool identified by toolID globally via npm and returns a
 * structured [InstallResult] carrying the exact command and npm's output. An
 * unknown toolID returns an error. When npm is missing the result is returned
 * (not an error) with a clear, user-facing message so the UI can show it.
 */
export function Install(toolID: string): $CancellablePromise<$models.InstallResult> {
    return $Call.ByID(941254115, toolID);
}

/**
 * ListProviders returns the non-secret views of every managed provider, in
 * stored order. With no providers configured it returns an empty list and no
 * error.
 */
export function ListProviders(): $CancellablePromise<$models.ProviderView[] | null> {
    return $Call.ByID(1125464194);
}

/**
 * ListTools returns one [ToolView] per registered adapter, in registration
 * order. Status is evaluated against the per-tool effective provider's
 * profile (a zero profile when none is configured). A per-tool Status error
 * is surfaced in Detail rather than failing the whole list.
 */
export function ListTools(): $CancellablePromise<$models.ToolView[] | null> {
    return $Call.ByID(3280393555);
}

/**
 * OnboardingDismissed reports whether the user dismissed the first-run
 * "Get started" checklist. Settings files saved before the flag existed
 * report false, so existing users simply see the checklist until their
 * state completes it (or they dismiss it).
 */
export function OnboardingDismissed(): $CancellablePromise<boolean> {
    return $Call.ByID(3634241590);
}

/**
 * PlanUninstall returns a non-secret, read-only preview of the action that
 * would currently be used to remove toolID. Unknown or unresolvable methods and
 * missing npm/brew are represented by CanExecute=false and a warning rather
 * than an error. The preview is never accepted by Uninstall; execution resolves
 * a fresh plan from toolID.
 */
export function PlanUninstall(toolID: string): $CancellablePromise<$models.UninstallPlan> {
    return $Call.ByID(1185264271, toolID);
}

/**
 * RemoveProvider deletes the provider with the given ID. Removing the active
 * provider promotes the first remaining one (none when the list empties).
 * Per-tool overrides pointing at the removed provider are pruned so those
 * tools fall back to the active provider.
 */
export function RemoveProvider(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(3145073925, providerID);
}

/**
 * RestoreAll restores every registered tool to its pre-apply state and returns a
 * per-tool outcome. It needs no profile; individual adapter failures are
 * captured per tool and do not abort the run.
 */
export function RestoreAll(): $CancellablePromise<$models.ToolOpResult[] | null> {
    return $Call.ByID(748026073);
}

/**
 * RestoreOne restores the single tool identified by toolID to its pre-apply
 * state. It returns an error for an unknown tool; a tool with nothing to restore
 * is a safe no-op handled by the adapter.
 */
export function RestoreOne(toolID: string): $CancellablePromise<core$0.RestoreResult> {
    return $Call.ByID(2514822234, toolID);
}

/**
 * SetActiveProvider selects the provider with the given ID as the globally
 * active one, used by every tool without a per-tool override.
 */
export function SetActiveProvider(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(4084510071, providerID);
}

/**
 * SetToolApplyMode records the per-tool apply mode for toolID: "all" applies
 * every model of the effective provider, "one" only the selected model. "one"
 * (the default) deletes the entry so the settings file stays minimal. The
 * toolID must be a registered tool and the mode one of the two values,
 * otherwise a clear error is returned. The selection is persisted via the
 * settings store.
 */
export function SetToolApplyMode(toolID: string, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3498050441, toolID, mode);
}

/**
 * SetToolModel records (or clears) the per-tool model selection for toolID.
 * An empty model deletes the selection so the tool uses the effective
 * provider's default. A non-empty model must be a member of the EFFECTIVE
 * provider's Models (the tool's provider override when set, else the active
 * provider), otherwise a clear error is returned. The toolID must be a
 * registered tool. The selection is persisted via the settings store.
 */
export function SetToolModel(toolID: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(2858844647, toolID, model);
}

/**
 * SetToolProvider records (or clears) the per-tool provider selection for
 * toolID. An empty providerID deletes the selection so the tool uses the
 * active provider. A non-empty providerID must reference a managed provider,
 * otherwise a clear error is returned. The toolID must be a registered tool.
 * The selection is persisted via the settings store.
 */
export function SetToolProvider(toolID: string, providerID: string): $CancellablePromise<void> {
    return $Call.ByID(4162388903, toolID, providerID);
}

/**
 * SweepLegacyMarkers strips the legacy in-file "mintswitchManaged" key from
 * every registered adapter that implements [core.LegacyMarkerStripper]
 * (migrating the marker into the sidecar store). It is best-effort: a failure
 * on one tool is logged, recorded per tool so ListTools surfaces it in that
 * tool's Detail, and never blocks the others or app startup.
 */
export function SweepLegacyMarkers(): $CancellablePromise<void> {
    return $Call.ByID(4002993474);
}

/**
 * Uninstall removes the tool identified by toolID using the method it was
 * actually installed with (npm, Homebrew, or a standalone binary), surfacing the
 * exact command (or delete action) and its output. Its return contract matches
 * [Service.Install]; when the install method cannot be determined it returns a
 * non-OK result carrying a clear, user-facing message instead of throwing.
 */
export function Uninstall(toolID: string): $CancellablePromise<$models.InstallResult> {
    return $Call.ByID(3584833602, toolID);
}

/**
 * UpdateProvider validates and persists changes to the provider identified by
 * p.ID. An empty incoming APIKey means "keep the stored one", so the UI can
 * submit the form without ever round-tripping a secret. Stale per-tool model
 * selections that pointed at models this provider no longer offers are pruned
 * (for tools whose effective provider is this one) so they fall back to the
 * provider default.
 */
export function UpdateProvider(p: core$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(2461295976, p);
}
