// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the backend façade bound into the Wails application.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyAll applies the active profile to every registered tool and returns a
 * per-tool outcome. It validates the saved profile once up front and fails fast
 * (returning an error, no partial results) when no valid profile is saved.
 * Individual adapter failures are captured per tool and do not abort the run.
 */
export function ApplyAll(): $CancellablePromise<$models.ToolOpResult[] | null> {
    return $Call.ByID(3266725423);
}

/**
 * ApplyOne applies the active profile to the single tool identified by toolID,
 * honoring the per-tool model selection. It first validates the saved profile
 * and returns an error for an unknown tool or an invalid/missing profile.
 */
export function ApplyOne(toolID: string): $CancellablePromise<core$0.ApplyResult> {
    return $Call.ByID(1465759944, toolID);
}

/**
 * GetProfile returns the non-secret view of the saved active profile. When no
 * profile is saved it returns a zero ProfileView (HasKey=false) and no error.
 */
export function GetProfile(): $CancellablePromise<$models.ProfileView> {
    return $Call.ByID(1851804553);
}

/**
 * Install installs the tool identified by toolID globally via npm and returns a
 * structured [InstallResult] carrying the exact command and npm's output. An
 * unknown toolID returns an error. When npm is missing the result is returned
 * (not an error) with a clear, user-facing message so the UI can show it.
 */
export function Install(toolID: string): $CancellablePromise<$models.InstallResult> {
    return $Call.ByID(941254115, toolID);
}

/**
 * ListTools returns one [ToolView] per registered adapter, in registration
 * order. Status is evaluated against the saved active profile (a zero profile
 * when none is saved). A per-tool Status error is surfaced in Detail rather than
 * failing the whole list.
 */
export function ListTools(): $CancellablePromise<$models.ToolView[] | null> {
    return $Call.ByID(3280393555);
}

/**
 * RestoreAll restores every registered tool to its pre-apply state and returns a
 * per-tool outcome. It needs no profile; individual adapter failures are
 * captured per tool and do not abort the run.
 */
export function RestoreAll(): $CancellablePromise<$models.ToolOpResult[] | null> {
    return $Call.ByID(748026073);
}

/**
 * RestoreOne restores the single tool identified by toolID to its pre-apply
 * state. It returns an error for an unknown tool; a tool with nothing to restore
 * is a safe no-op handled by the adapter.
 */
export function RestoreOne(toolID: string): $CancellablePromise<core$0.RestoreResult> {
    return $Call.ByID(2514822234, toolID);
}

/**
 * SaveProfile validates and persists p as the active profile. An empty incoming
 * APIKey is treated as "keep the existing key" so the masked UI can submit the
 * form without re-sending the secret; the merged profile is then validated via
 * [core.Profile.Validate] and an invalid profile is rejected with an error.
 */
export function SaveProfile(p: core$0.Profile): $CancellablePromise<void> {
    return $Call.ByID(4257341798, p);
}

/**
 * SetToolModel records (or clears) the per-tool model selection for toolID. An
 * empty model deletes the selection so the tool uses the profile default. A
 * non-empty model must be a member of the active profile's Models, otherwise a
 * clear error is returned. The toolID must be a registered tool. The selection
 * is persisted via the settings store.
 */
export function SetToolModel(toolID: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(2858844647, toolID, model);
}

/**
 * SweepLegacyMarkers strips the legacy in-file "mintswitchManaged" key from
 * every registered adapter that implements [core.LegacyMarkerStripper]
 * (migrating the marker into the sidecar store). It is best-effort: a failure
 * on one tool is logged, recorded per tool so ListTools surfaces it in that
 * tool's Detail, and never blocks the others or app startup.
 */
export function SweepLegacyMarkers(): $CancellablePromise<void> {
    return $Call.ByID(4002993474);
}

/**
 * Uninstall removes the tool identified by toolID using the method it was
 * actually installed with (npm, Homebrew, or a standalone binary), surfacing the
 * exact command (or delete action) and its output. Its return contract matches
 * [Service.Install]; when the install method cannot be determined it returns a
 * non-OK result carrying a clear, user-facing message instead of throwing.
 */
export function Uninstall(toolID: string): $CancellablePromise<$models.InstallResult> {
    return $Call.ByID(3584833602, toolID);
}
