// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplyResult summarizes the outcome of [ToolAdapter.Apply].
 */
export interface ApplyResult {
    /**
     * ChangedPath is the tool config file that was written.
     */
    "changed_path"?: string;

    /**
     * BackupPath is the backup created before the change, if any.
     */
    "backup_path"?: string;

    /**
     * Message is a human-readable summary, safe to display (no secrets).
     */
    "message"?: string;
}

/**
 * Profile is a single OpenAI-compatible endpoint configuration that the user
 * wants to apply to one or more AI coding tools.
 * 
 * API keys live in this struct; callers must never write APIKey to logs.
 */
export interface Profile {
    /**
     * Label is an optional human-friendly name for the profile.
     */
    "label"?: string;

    /**
     * APIKey is the secret bearer token for the endpoint. Required.
     */
    "api_key": string;

    /**
     * BaseURL is the OpenAI-compatible base URL (http or https). Required.
     */
    "base_url": string;

    /**
     * Model is the default model identifier. Required.
     */
    "model": string;

    /**
     * SmallFastModel is an optional secondary model used by some tools for
     * lightweight/background tasks.
     */
    "small_fast_model"?: string;
}

/**
 * RestoreResult summarizes the outcome of [ToolAdapter.Restore].
 */
export interface RestoreResult {
    /**
     * ChangedPath is the tool config file that was restored or removed.
     */
    "changed_path"?: string;

    /**
     * BackupPath is the backup that was used to restore, if any.
     */
    "backup_path"?: string;

    /**
     * Message is a human-readable summary, safe to display (no secrets).
     */
    "message"?: string;
}
