// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApplyResult summarizes the outcome of [ToolAdapter.Apply].
 */
export interface ApplyResult {
    /**
     * ChangedPath is the tool config file that was written.
     */
    "changed_path"?: string;

    /**
     * BackupPath is the backup created before the change, if any.
     */
    "backup_path"?: string;

    /**
     * Message is a human-readable summary, safe to display (no secrets).
     */
    "message"?: string;
}

/**
 * Provider is one named OpenAI-compatible endpoint the user manages: an API
 * key plus the endpoint fields adapters need, under a user-chosen display
 * name. The application holds a list of Providers and resolves one per tool
 * into the [Profile] adapters consume.
 * 
 * Name and Note are non-secret display text (persisted in the settings file
 * and shown over bindings); the APIKey value must never be logged or sent to
 * the frontend, not even masked.
 */
export interface Provider {
    /**
     * ID uniquely identifies the provider within the state.
     */
    "id": string;

    /**
     * Name is the user-chosen display name (e.g. "OpenAI").
     */
    "name": string;

    /**
     * Note is optional free-text shown alongside the name. Never secret.
     */
    "note"?: string;

    /**
     * APIKey is the secret bearer token. Required. Persisted keychain-first;
     * never logged or returned to the frontend.
     */
    "api_key"?: string;

    /**
     * BaseURL is the OpenAI-compatible base URL (http or https). Required.
     */
    "base_url": string;

    /**
     * Models is the provider's saved set of selectable model identifiers. The
     * default selection is Model, which must be a member when Models is
     * non-empty.
     */
    "models"?: string[] | null;

    /**
     * ModelNames optionally maps a member of Models to a human-friendly
     * display name shown by the UI.
     */
    "model_names"?: { [_ in string]?: string } | null;

    /**
     * ModelContextWindows optionally maps a member of Models to the context
     * window (in tokens) the endpoint's /models listing advertised for it.
     * Adapters fall back to a tool-specific default for missing entries.
     */
    "model_context_windows"?: { [_ in string]?: number } | null;

    /**
     * Model is the provider's default model identifier. Required.
     */
    "model": string;

    /**
     * SmallFastModel is an optional secondary model used by some tools for
     * lightweight/background tasks. It need not be a member of Models.
     */
    "small_fast_model"?: string;

    /**
     * OpusModel, SonnetModel, HaikuModel and FableModel optionally pin Claude
     * Code's model tiers (opus/sonnet/haiku/fable aliases). Empty tiers fall
     * back to Model (Haiku prefers SmallFastModel). They need not be members
     * of Models.
     */
    "opus_model"?: string;
    "sonnet_model"?: string;
    "haiku_model"?: string;
    "fable_model"?: string;

    /**
     * ReviewModel optionally pins the model Codex uses for its code-review
     * flow. Only the codex adapter reads it; empty means reviews follow the
     * session model (no key is written). It need not be a member of Models.
     */
    "review_model"?: string;
}

/**
 * RestoreResult summarizes the outcome of [ToolAdapter.Restore].
 */
export interface RestoreResult {
    /**
     * ChangedPath is the tool config file that was restored or removed.
     */
    "changed_path"?: string;

    /**
     * BackupPath is the backup that was used to restore, if any.
     */
    "backup_path"?: string;

    /**
     * Message is a human-readable summary, safe to display (no secrets).
     */
    "message"?: string;
}
